### ISSUE TITLE
中文无法搜索

### ISSUE THREAD

**Issue by 1dunTNT** [kazhafeizhale/explore_select_items#1]
https://www.autoahk.com/archives/37358
视频中演示的中文能搜索
但是实际搜索不了中文，只能搜英文
比如目录下包含“用户”文件夹，搜索yonghu无结果

**Comment by kazhafeizhale** [comment]
有没有试过其他目录，
如果输入空格看看是不是当前文件都会列出来
gif可以上传

**Comment by 1dunTNT** [comment]
1 其他目录情况一样；
2 输入空格能列出来所有文件夹；
操作见gif
https://github.com/1dunTNT/test/blob/main/%E5%8A%A8%E7%94%BB.gif?raw=true

**Comment by kazhafeizhale** [comment]
> 

估计和win11有关系，我电脑都是win10的

**Comment by 1dunTNT** [comment]
乌龙了，用你的新链接下载了压缩包。
运行exe提示“资源管理器拼音搜索.ahk”不存在，我才意识到可能是exe和ahk文件都需要。
重新zip完美可以用。
之前只下载exe文件。谢谢大佬。
